### ISSUE TITLE
Design frontend

### ISSUE THREAD

**Issue by retrokiller543** [DV1512/frontend#4]
# Design the Frontend in Figma

This should be a almost 100% representation of how the website/app should look like when complete

## After completion

If possible comment with a link to the design here so its easy to find it

**Comment by EmEhPa** [comment]
Finnished, see figma. Link will be uploaded shortly

**Comment by EmEhPa** [comment]
### In png format
![Image](https://github.com/user-attachments/assets/d4cde56b-44ee-4d9d-9d52-dcb425a9fc8f)

### The link, OBS!! you need to have an account on figma
https://www.figma.com/proto/eFM71NNPeonpgeBCsuJ7PN/ThreatMapper?node-id=0-1&t=VqrF80GamVObjb2G-1

**Comment by EmEhPa** [comment]
Be aware that this is just a design draft. During implementation, things/details can be changed, e.g. background color etc.
